// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcq5xbgPS8GX_K2PHGTx0i7fUlP0gRVnU',
    appId: '1:278498957019:web:6fc2f9edf740d16272defe',
    messagingSenderId: '278498957019',
    projectId: 'my-resume-c86d8',
    authDomain: 'my-resume-c86d8.firebaseapp.com',
    storageBucket: 'my-resume-c86d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIClgkCdNveW5J3vHVsagAs9ZGl_X5AvM',
    appId: '1:278498957019:android:2268e9bf9a2d974772defe',
    messagingSenderId: '278498957019',
    projectId: 'my-resume-c86d8',
    storageBucket: 'my-resume-c86d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFCU8FMhntuoxAbgYW_DNz56LY9wrW7g',
    appId: '1:278498957019:ios:a73db97bf637023b72defe',
    messagingSenderId: '278498957019',
    projectId: 'my-resume-c86d8',
    storageBucket: 'my-resume-c86d8.appspot.com',
    iosBundleId: 'com.example.myresume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuFCU8FMhntuoxAbgYW_DNz56LY9wrW7g',
    appId: '1:278498957019:ios:0d5f8feff760355372defe',
    messagingSenderId: '278498957019',
    projectId: 'my-resume-c86d8',
    storageBucket: 'my-resume-c86d8.appspot.com',
    iosBundleId: 'com.example.myresume.RunnerTests',
  );
}
